using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommonDbLib
{
    public class DataSheetLv3
    {
        [Key]
        public int SheetNo { get; set; }
        [MaxLength(50)]
        public string? TagNo { get; set; }
        [MaxLength(50)]
        public string? EstimateNo { get; set; }
        [ForeignKey("EstimateNo")]
        public EstimateSheetLv1? EstimateSheet { get; set; }
        [MaxLength(50)]
        public string? ItemCode { get; set; }
        [ForeignKey("ItemCode")]
        public ItemList? Item { get; set; }
        public int? UnitPrice { get; set; }
        public int? Quantity { get; set; }
        public string? Project { get; set; }
        public string? Service { get; set; }
        public string? MFGNo { get; set; }
        public string? ModelNo { get; set; }
        public string? Medium { get; set; }
        public string? State { get; set; }
        public string? FlowRateUnit { get; set; }
        public decimal? FlowRateMaxQ { get; set; }
        public decimal? FlowRateNorQ { get; set; }
        public decimal? FlowRateMinQ { get; set; }
        public string? InletPressureUnit { get; set; }
        public decimal? InletPressureMaxQ { get; set; }
        public decimal? InletPressureNorQ { get; set; }
        public decimal? InletPressureMinQ { get; set; }
        public string? OutletPressureUnit { get; set; }
        public decimal? OutletPressureMaxQ { get; set; }
        public decimal? OutletPressureNorQ { get; set; }
        public decimal? OutletPressureMinQ { get; set; }
        public string? DifferentialPressureUnit { get; set; }
        public decimal? DifferentialPressureMaxQ { get; set; }
        public decimal? DifferentialPressureNorQ { get; set; }
        public decimal? DifferentialPressureMinQ { get; set; }
        public string? InletTemperatureUnit { get; set; }
        public decimal? InletTemperatureQ { get; set; }
        public decimal? InletTemperatureNorQ { get; set; }
        public decimal? InletTemperatureMinQ { get; set; }
        public string? SpecificGravityUnit { get; set; }
        public decimal? SpecificGravityMaxQ { get; set; }
        public decimal? SpecificGravityNorQ { get; set; }
        public decimal? SpecificGravityMinQ { get; set; }
        public string? DensityUnit { get; set; }
        public decimal? DensityMaxQ { get; set; }
        public decimal? DensityNorQ { get; set; }
        public decimal? DensityMinQ { get; set; }
        public string? MolecularWeightUnit { get; set; }
        public decimal? MolecularWeightMaxQ { get; set; }
        public decimal? MolecularWeightNorQ { get; set; }
        public decimal? MolecularWeightMinQ { get; set; }
        public string? ViscosityUnit { get; set; }
        public decimal? ViscosityMaxQ { get; set; }
        public decimal? ViscosityNorQ { get; set; }
        public decimal? ViscosityMinQ { get; set; }
        public string? PredictedSPLUnit { get; set; }
        public string? PredictedSPLMaxQ { get; set; }
        public string? PredictedSPLNorQ { get; set; }
        public string? PredictedSPLMinQ { get; set; }
        public string? CalculatedCvUnit { get; set; }
        public decimal? CalculatedCvMaxQ { get; set; }
        public decimal? CalculatedCvNorQ { get; set; }
        public decimal? CalculatedCvMinQ { get; set; }
        public string? OpeningLiftUnit { get; set; }
        public decimal? OpeningLiftMaxQ { get; set; }
        public decimal? OpeningLiftNorQ { get; set; }
        public decimal? OpeningLiftMinQ { get; set; }
        public string? ShutOffDPUnit { get; set; }
        public decimal? ShutOffDP { get; set; }
        public string? PressureUnit { get; set; }
        public decimal? Pressure { get; set; }
        public string? TempUnit { get; set; }
        public string? Temp { get; set; }
        public string? InletPipeSize { get; set; }
        public string? InletPipeSizeSchNo { get; set; }
        public string? OutletPipeSize { get; set; }
        public string? OutletPipeSizeSchNo { get; set; }
        public string? BNTBodyType { get; set; }
        public string? BNTBodySize { get; set; }
        public string? BNTPortSize { get; set; }
        public string? BNTTrimDesign { get; set; }
        public string? BNTTrimType { get; set; }
        public string? BNTTrimSealRing { get; set; }
        public string? BNTGuide { get; set; }
        public string? BNTRating { get; set; }
        public string? BNTEndConnection { get; set; }
        public string? BNTFlangeFacing { get; set; }
        public string? BNTBody { get; set; }
        public string? BNTTrim { get; set; }
        public string? BNTStem { get; set; }
        public string? BNTPacking { get; set; }
        public string? BNTSpecialName { get; set; }
        public string? BNTSpecial { get; set; }
        public string? BNTBonnetType { get; set; }
        public string? BNTTrimForm { get; set; }
        public string? BNTMaxAllowSoundLevel_dBA { get; set; }
        public string? BNTRequiredSeatTightness { get; set; }
        public decimal? BNTRatedCv { get; set; }
        public string? BNTStroke { get; set; }
        public string? BNTFlowActionTo { get; set; }
        public string? BNTPaintingColor { get; set; }
        public string? BNTPaintingType { get; set; }
        public string? BNTOilFreeWaterFreeTreatment { get; set; }
        public string? ActuatorType { get; set; }
        public string? ActuatorModelNo { get; set; }
        public decimal? ActuatorCloseAt { get; set; }
        public decimal? ActuatorOpenAt { get; set; }
        public string? ActuatorFailPosition { get; set; }
        public string? ActuatorPaintingColor { get; set; }
        public string? ActuatorPaintingType { get; set; }
        public string? HWTypeLocation { get; set; }
        public string? HWPaintingColor { get; set; }
        public string? HWPaintingType { get; set; }
        public string? IPPosInputSignal { get; set; }
        public string? IPPosType { get; set; }
        public string? IPPosEnclosure { get; set; }
        public string? IPPosModelNo { get; set; }
        public string? IPPosMFG { get; set; }
        public string? PosTransOutput { get; set; }
        public string? PosTransType { get; set; }
        public decimal? AirSetSupplySettingPressure { get; set; }
        public string? AirSetModelNo { get; set; }
        public string? AirSetMFG { get; set; }
        public string? SolValvePower { get; set; }
        public string? SolValveType { get; set; }
        public string? SolValveEnclosure { get; set; }
        public string? SolValveModelNo { get; set; }
        public string? SolValveMFG { get; set; }
        public string? LimSwitchQuantity { get; set; }
        public string? LimSwitchType { get; set; }
        public string? LimSwitchEnclosure { get; set; }
        public string? LimSwitchModelNo { get; set; }
        public string? LimSwitchMFG { get; set; }
        public string? LockUpValveSettingPressure { get; set; }
        public string? LockUpValveModelNo { get; set; }
        public string? SnapActSettingPressure { get; set; }
        public string? SnapActModelNo { get; set; }
        public string? AccAirOperatedValve { get; set; }
        public string? AccMechanicalValve { get; set; }
        public string? AccCheckValve { get; set; }
        public string? AccVolumeBooster { get; set; }
        public string? AccExhaustValve { get; set; }
        public string? AccSpeedController { get; set; }
        public string? AccSilencer { get; set; }
        public string? MiscellAirSupply { get; set; }
        public string? MiscellElectrical { get; set; }
        public string? MiscellWaterSeal { get; set; }
        public string? MiscellJacket { get; set; }
        public string? MiscellJacketMaterial { get; set; }
        public string? MiscellTubingMaterial { get; set; }
        public string? MiscellSunshadeMaterial { get; set; }
        public string? Note { get; set; }
        public string? No { get; set; }
        public DateTime? Date { get; set; }
        public string? Revision { get; set; }
        public string? PreparedBy { get; set; }
        public string? CheckedBy { get; set; }
        public string? ApprovedBy { get; set; }
        public DateTime? CVDate { get; set; }
        public int? CVNo { get; set; }
        public string? CVRemark { get; set; }
        public int? VALNo { get; set; }
        public string? VALJacket { get; set; }
        public bool? VALBR { get; set; }
        public bool? VALWS { get; set; }
        public bool? VALSS { get; set; }
        public string? VALDeviation { get; set; }
        public string? VALRemak { get; set; }
        public int? VALTotal { get; set; }
        public string? VALBoosterRelay { get; set; }
    }
} 