// <auto-generated />
using System;
using CommonDbLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonDbLib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723045125_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CommonDbLib.DataSheetLv3", b =>
                {
                    b.Property<int>("SheetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccAirOperatedValve")
                        .HasColumnType("longtext");

                    b.Property<string>("AccCheckValve")
                        .HasColumnType("longtext");

                    b.Property<string>("AccExhaustValve")
                        .HasColumnType("longtext");

                    b.Property<string>("AccMechanicalValve")
                        .HasColumnType("longtext");

                    b.Property<string>("AccSilencer")
                        .HasColumnType("longtext");

                    b.Property<string>("AccSpeedController")
                        .HasColumnType("longtext");

                    b.Property<string>("AccVolumeBooster")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ActuatorCloseAt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ActuatorFailPosition")
                        .HasColumnType("longtext");

                    b.Property<string>("ActuatorModelNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ActuatorOpenAt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ActuatorPaintingColor")
                        .HasColumnType("longtext");

                    b.Property<string>("ActuatorPaintingType")
                        .HasColumnType("longtext");

                    b.Property<string>("ActuatorType")
                        .HasColumnType("longtext");

                    b.Property<string>("AirSetMFG")
                        .HasColumnType("longtext");

                    b.Property<string>("AirSetModelNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AirSetSupplySettingPressure")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTBody")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTBodySize")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTBodyType")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTBonnetType")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTEndConnection")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTFlangeFacing")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTFlowActionTo")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTGuide")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTMaxAllowSoundLevel_dBA")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTOilFreeWaterFreeTreatment")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTPacking")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTPaintingColor")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTPaintingType")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTPortSize")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("BNTRatedCv")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BNTRating")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTRequiredSeatTightness")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTSpecial")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTSpecialName")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTStem")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTStroke")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTTrim")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTTrimDesign")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTTrimForm")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTTrimSealRing")
                        .HasColumnType("longtext");

                    b.Property<string>("BNTTrimType")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CVDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CVNo")
                        .HasColumnType("int");

                    b.Property<string>("CVRemark")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CalculatedCvMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CalculatedCvMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CalculatedCvNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CalculatedCvUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DensityMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DensityMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DensityNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DensityUnit")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DifferentialPressureMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DifferentialPressureMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DifferentialPressureNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DifferentialPressureUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("EstimateNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("FlowRateMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("FlowRateMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("FlowRateNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FlowRateUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("HWPaintingColor")
                        .HasColumnType("longtext");

                    b.Property<string>("HWPaintingType")
                        .HasColumnType("longtext");

                    b.Property<string>("HWTypeLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("IPPosEnclosure")
                        .HasColumnType("longtext");

                    b.Property<string>("IPPosInputSignal")
                        .HasColumnType("longtext");

                    b.Property<string>("IPPosMFG")
                        .HasColumnType("longtext");

                    b.Property<string>("IPPosModelNo")
                        .HasColumnType("longtext");

                    b.Property<string>("IPPosType")
                        .HasColumnType("longtext");

                    b.Property<string>("InletPipeSize")
                        .HasColumnType("longtext");

                    b.Property<string>("InletPipeSizeSchNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("InletPressureMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InletPressureMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InletPressureNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("InletPressureUnit")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("InletTemperatureMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InletTemperatureNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InletTemperatureQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("InletTemperatureUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LimSwitchEnclosure")
                        .HasColumnType("longtext");

                    b.Property<string>("LimSwitchMFG")
                        .HasColumnType("longtext");

                    b.Property<string>("LimSwitchModelNo")
                        .HasColumnType("longtext");

                    b.Property<string>("LimSwitchQuantity")
                        .HasColumnType("longtext");

                    b.Property<string>("LimSwitchType")
                        .HasColumnType("longtext");

                    b.Property<string>("LockUpValveModelNo")
                        .HasColumnType("longtext");

                    b.Property<string>("LockUpValveSettingPressure")
                        .HasColumnType("longtext");

                    b.Property<string>("MFGNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Medium")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellAirSupply")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellElectrical")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellJacket")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellJacketMaterial")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellSunshadeMaterial")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellTubingMaterial")
                        .HasColumnType("longtext");

                    b.Property<string>("MiscellWaterSeal")
                        .HasColumnType("longtext");

                    b.Property<string>("ModelNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("MolecularWeightMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MolecularWeightMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MolecularWeightNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MolecularWeightUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("No")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OpeningLiftMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OpeningLiftMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OpeningLiftNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OpeningLiftUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("OutletPipeSize")
                        .HasColumnType("longtext");

                    b.Property<string>("OutletPipeSizeSchNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OutletPressureMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OutletPressureMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OutletPressureNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OutletPressureUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("PosTransOutput")
                        .HasColumnType("longtext");

                    b.Property<string>("PosTransType")
                        .HasColumnType("longtext");

                    b.Property<string>("PredictedSPLMaxQ")
                        .HasColumnType("longtext");

                    b.Property<string>("PredictedSPLMinQ")
                        .HasColumnType("longtext");

                    b.Property<string>("PredictedSPLNorQ")
                        .HasColumnType("longtext");

                    b.Property<string>("PredictedSPLUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("PreparedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PressureUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("Project")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Revision")
                        .HasColumnType("longtext");

                    b.Property<string>("Service")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ShutOffDP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ShutOffDPUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("SnapActModelNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SnapActSettingPressure")
                        .HasColumnType("longtext");

                    b.Property<string>("SolValveEnclosure")
                        .HasColumnType("longtext");

                    b.Property<string>("SolValveMFG")
                        .HasColumnType("longtext");

                    b.Property<string>("SolValveModelNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SolValvePower")
                        .HasColumnType("longtext");

                    b.Property<string>("SolValveType")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SpecificGravityMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SpecificGravityMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SpecificGravityNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SpecificGravityUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("TagNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temp")
                        .HasColumnType("longtext");

                    b.Property<string>("TempUnit")
                        .HasColumnType("longtext");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("int");

                    b.Property<bool?>("VALBR")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VALBoosterRelay")
                        .HasColumnType("longtext");

                    b.Property<string>("VALDeviation")
                        .HasColumnType("longtext");

                    b.Property<string>("VALJacket")
                        .HasColumnType("longtext");

                    b.Property<int?>("VALNo")
                        .HasColumnType("int");

                    b.Property<string>("VALRemak")
                        .HasColumnType("longtext");

                    b.Property<bool?>("VALSS")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("VALTotal")
                        .HasColumnType("int");

                    b.Property<bool?>("VALWS")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("ViscosityMaxQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ViscosityMinQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ViscosityNorQ")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ViscosityUnit")
                        .HasColumnType("longtext");

                    b.HasKey("SheetNo");

                    b.HasIndex("EstimateNo");

                    b.HasIndex("ItemCode");

                    b.ToTable("DataSheetLv3s");
                });

            modelBuilder.Entity("CommonDbLib.EstimateSheetLv1", b =>
                {
                    b.Property<string>("CurEstimateNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CurEstPrice")
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ManagerUserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrevEstimateNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CurEstimateNo");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ManagerUserID");

                    b.ToTable("EstimateSheetLv1s");
                });

            modelBuilder.Entity("CommonDbLib.ItemList", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ItemCode");

                    b.ToTable("ItemLists");
                });

            modelBuilder.Entity("CommonDbLib.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CommonDbLib.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CommonDbLib.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BusinessNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommonDbLib.DataSheetLv3", b =>
                {
                    b.HasOne("CommonDbLib.EstimateSheetLv1", "EstimateSheet")
                        .WithMany()
                        .HasForeignKey("EstimateNo");

                    b.HasOne("CommonDbLib.ItemList", "Item")
                        .WithMany()
                        .HasForeignKey("ItemCode");

                    b.Navigation("EstimateSheet");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CommonDbLib.EstimateSheetLv1", b =>
                {
                    b.HasOne("CommonDbLib.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonDbLib.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerUserID");

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CommonDbLib.User", b =>
                {
                    b.HasOne("CommonDbLib.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CommonDbLib.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
