-- 데이터베이스 드롭 및 재생성
DROP DATABASE IF EXISTS PWD_Final;
CREATE DATABASE PWD_Final;
USE PWD_Final;

-- 1) AccMakerList 테이블들 (먼저 생성되어야 함)
create table PositionerMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table SolenoidMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table LimitMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table AirsetMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table VolumeMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table AiroperateMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table LockupMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

create table snapactingMakerList(
  AccMakerCode CHAR(1) NOT NULL,
  AccMakerName VARCHAR(100) NOT NULL,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (AccMakerCode)
);

-- 2) AccList 테이블들 (AccMakerList 참조)
CREATE TABLE PositionerList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Positioner_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES PositionerMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT  
);

CREATE TABLE SolenoidList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL, 
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Solenoid_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES SolenoidMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE LimitList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Limit_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES LimitMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE AirsetList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Airset_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES AirsetMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE VolumeList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Volume_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES VolumeMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE AiroperateList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Airoperate_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES AiroperateMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE LockupList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Lockup_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES LockupMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);  

CREATE TABLE SnapactingList(
    AccMakerCode CHAR(1) NOT NULL,
    AccModelCode CHAR(1) NOT NULL,
	AccModelName VARCHAR(255) NOT NULL,
    AccSize VARCHAR(255) NULL DEFAULT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (AccMakerCode, AccModelCode),
    CONSTRAINT FK_Snapacting_AccMaker FOREIGN KEY (AccMakerCode) REFERENCES SnapactingMakerList(AccMakerCode) ON UPDATE CASCADE ON DELETE RESTRICT
);



-- 4) Body 관련 테이블
CREATE TABLE BodyValveList (
  ValveSeries VARCHAR(255) UNIQUE,
  ValveSeriesCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE BodyBonnetList (
  BonnetType VARCHAR(255) UNIQUE,
  BonnetCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE BodyMatList (
  BodyMat VARCHAR(255) UNIQUE,
  BodyMatCode CHAR(1) PRIMARY KEY NOT NULL
);

-- Body Size Unit 테이블
CREATE TABLE BodySizeUnit (
  UnitCode CHAR(1) NOT NULL,
  UnitName VARCHAR(50) NOT NULL,
  PRIMARY KEY (UnitCode),
  UNIQUE (UnitName)
);

CREATE TABLE BodySizeList (
  UnitCode CHAR(1) NOT NULL,
  BodySize VARCHAR(255),
  BodySizeCode CHAR(1) NOT NULL,
  PRIMARY KEY (UnitCode, BodySizeCode),
  CONSTRAINT FK_BodySize_BodyUnit FOREIGN KEY (UnitCode) REFERENCES BodySizeUnit(UnitCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE BodyRatingUnitList (
  RatingUnitCode CHAR(1) NOT NULL,
  RatingUnit VARCHAR(255) NOT NULL,
  PRIMARY KEY (RatingUnitCode)
);

CREATE TABLE BodyRatingList (
  RatingUnitCode CHAR(1) NOT NULL,
  RatingCode CHAR(1) NOT NULL,
  RatingName VARCHAR(255) NOT NULL,
  PRIMARY KEY (RatingUnitCode, RatingCode),
  CONSTRAINT FK_BodyRating_RatingUnit FOREIGN KEY (RatingUnitCode) REFERENCES BodyRatingUnitList(RatingUnitCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE BodyConnectionList (
  Connection VARCHAR(255) UNIQUE,
  ConnectionCode CHAR(1) PRIMARY KEY NOT NULL
);

-- 5) Trim 관련 테이블
CREATE TABLE TrimTypeList (
  TrimType VARCHAR(255) UNIQUE,
  TrimTypeCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE TrimSeriesList (
  TrimSeries VARCHAR(255) UNIQUE,
  TrimSeriesCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE TrimMatList (
  TrimMat VARCHAR(255) UNIQUE,
  TrimMatCode CHAR(1) PRIMARY KEY NOT NULL
);

-- Trim Port Size Unit 테이블
CREATE TABLE TrimPortSizeUnit (
  UnitCode CHAR(1) NOT NULL,
  UnitName VARCHAR(50) NOT NULL,
  PRIMARY KEY (UnitCode),
  UNIQUE (UnitName)
);

CREATE TABLE TrimPortSizeList (
  PortSizeCode CHAR(1),
  UnitCode CHAR(1) NOT NULL,
  PortSize VARCHAR(255) NOT NULL,
  PRIMARY KEY (PortSizeCode, UnitCode),
  CONSTRAINT FK_TrimPortSize_TrimUnit FOREIGN KEY (UnitCode) REFERENCES TrimPortSizeUnit(UnitCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE TrimFormList (
  TrimForm VARCHAR(255) UNIQUE,
  TrimFormCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE TrimOptionList (
  TrimOptionCode CHAR(1) PRIMARY KEY,
  TrimOptionName VARCHAR(255) NOT NULL
);

-- 6) Act 관련 테이블
CREATE TABLE ActTypeList (
  ActType VARCHAR(255) UNIQUE,
  ActTypeCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE ActSeriesList (
  ActSeries VARCHAR(255),
  ActSeriesCode CHAR(1) PRIMARY KEY NOT NULL
);

CREATE TABLE ActSizeList (
  ActSeriesCode CHAR(1) NOT NULL,
  ActSize VARCHAR(255),
  ActSizeCode CHAR(1) NOT NULL,
  PRIMARY KEY (ActSeriesCode, ActSizeCode),
  CONSTRAINT FK_ActSize_ActSeries FOREIGN KEY (ActSeriesCode) REFERENCES ActSeriesList(ActSeriesCode) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE ActHWList (
  HW VARCHAR(255) UNIQUE,
  HWCode CHAR(1) PRIMARY KEY NOT NULL
);

-- 7) Role 테이블
CREATE TABLE Role (
  RoleID INT PRIMARY KEY NOT NULL,
  RoleName VARCHAR(255) NOT NULL,
  Description VARCHAR(255)
);

-- 8) User 테이블
CREATE TABLE User (
  UserID VARCHAR(255) PRIMARY KEY NOT NULL,
  Password VARCHAR(255) NOT NULL,
  CompanyName VARCHAR(255) NOT NULL,
  CompanyPhone VARCHAR(255) NOT NULL,
  RoleID INT NOT NULL,
  Position VARCHAR(255) NOT NULL,
  Department VARCHAR(255) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  BusinessNumber VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  PhoneNumber VARCHAR(255) UNIQUE NOT NULL,
  IsApproved BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT FK_User_Role FOREIGN KEY (RoleID)
    REFERENCES Role(RoleID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 9) EstimateSheetLv1 테이블
CREATE TABLE EstimateSheetLv1 (
  TempEstimateNo VARCHAR(255) PRIMARY KEY,
  CurEstimateNo VARCHAR(255) UNIQUE NULL,
  PrevEstimateNo VARCHAR(255),
  CustomerID VARCHAR(255),
  WriterID VARCHAR(255),
  ManagerID VARCHAR(255),
  Status INT NOT NULL,
  Project VARCHAR(255),
  CustomerRequirement TEXT,
  StaffComment TEXT,
  CONSTRAINT FK_EstimateSheet_Customer FOREIGN KEY (CustomerID) REFERENCES User(UserID) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_EstimateSheet_Writer FOREIGN KEY (WriterID) REFERENCES User(UserID) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_EstimateSheet_Manager FOREIGN KEY (ManagerID) REFERENCES User(UserID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 10) EstimateRequest 테이블
CREATE TABLE EstimateRequest (
  EstimateNo VARCHAR(255),
  TempEstimateNo VARCHAR(255) NOT NULL,
  SheetID INT NOT NULL,
  SheetNo INT NOT NULL,
  ValveType CHAR(1) NULL,
  Tagno VARCHAR(255) NOT NULL,
  UnitPrice INT,
  Qty INT,
  Medium VARCHAR(255),
  Fluid VARCHAR(255),
  IsQM BOOLEAN,
  IsP2 BOOLEAN,
  IsDensity BOOLEAN,
  IsHW BOOLEAN,
  QMUnit VARCHAR(255),
  QMMax DECIMAL(10,5),
  QMNor DECIMAL(10,5),
  QMMin DECIMAL(10,5),
  QNUnit VARCHAR(255),
  QNMax DECIMAL(10,5),
  QNNor DECIMAL(10,5),
  QNMin DECIMAL(10,5),
  PressureUnit VARCHAR(255),
  InletPressureMaxQ DECIMAL(10,5),
  InletPressureNorQ DECIMAL(10,5),
  InletPressureMinQ DECIMAL(10,5),
  OutletPressureMaxQ DECIMAL(10,5),
  OutletPressureNorQ DECIMAL(10,5),
  OutletPressureMinQ DECIMAL(10,5),
  DifferentialPressureMaxQ DECIMAL(10,5),
  DifferentialPressureNorQ DECIMAL(10,5),
  DifferentialPressureMinQ DECIMAL(10,5),
  TemperatureUnit VARCHAR(255),
  InletTemperatureQ DECIMAL(10,5),
  InletTemperatureNorQ DECIMAL(10,5),
  InletTemperatureMinQ DECIMAL(10,5),
  DensityUnit VARCHAR(255),
  Density DECIMAL(10,5),
  MolecularWeightUnit VARCHAR(255),
  MolecularWeight DECIMAL(10,5),
  BodySizeUnit CHAR(1) NULL,
  BodySize CHAR(1) NULL,
  BodyMat CHAR(1) NULL,
  TrimMat CHAR(1) NULL,
  TrimOption CHAR(1) NULL,
  BodyRating CHAR(1) NULL,
  BodyRatingUnit CHAR(1) NULL,
  ActType VARCHAR(255) NULL,
  IsPositioner BOOLEAN,
  PositionerType VARCHAR(255),
  ExplosionProof VARCHAR(255),
  TransmitterType VARCHAR(255),
  IsSolenoid BOOLEAN,
  IsLimSwitch BOOLEAN,
  IsAirSet BOOLEAN,
  IsVolumeBooster BOOLEAN,
  IsAirOperated BOOLEAN,
  IsLockUp BOOLEAN,
  IsSnapActingRelay BOOLEAN,
  PRIMARY KEY (TempEstimateNo, SheetID),
  CONSTRAINT FK_EstimateRequest_TempEstimateNo FOREIGN KEY (TempEstimateNo) REFERENCES EstimateSheetLv1(TempEstimateNo) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 11) EstimateAttachment 테이블
CREATE TABLE EstimateAttachment (
  AttachmentID INT AUTO_INCREMENT PRIMARY KEY,
  TempEstimateNo VARCHAR(255) NOT NULL,
  FileName VARCHAR(255) NOT NULL,
  FilePath VARCHAR(500) NOT NULL,
  FileSize INT,
  UploadDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  UploadUserID VARCHAR(255),
  ManagerFileType VARCHAR(50) DEFAULT '',
  CONSTRAINT FK_EstimateAttachment_TempEstimateNo FOREIGN KEY (TempEstimateNo) REFERENCES EstimateSheetLv1(TempEstimateNo) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_EstimateAttachment_UploadUser FOREIGN KEY (UploadUserID) REFERENCES User(UserID) ON UPDATE CASCADE ON DELETE SET NULL
);

-- 12) DataSheetLv3 테이블
CREATE TABLE DataSheetLv3 (
  EstimateNo VARCHAR(255) NULL DEFAULT NULL,
  TempEstimateNo VARCHAR(255) NOT NULL,
  SheetID INT NOT NULL,
  Medium VARCHAR(255) NULL DEFAULT NULL,
  Fluid VARCHAR(255) NULL DEFAULT NULL,
  IsQM BOOLEAN NULL DEFAULT NULL,
  IsP2 BOOLEAN NULL DEFAULT NULL,
  IsDensity BOOLEAN NULL DEFAULT NULL,
  IsN1 BOOLEAN NULL DEFAULT NULL,
  QMUnit VARCHAR(255) NULL DEFAULT NULL,
  QMMax DECIMAL(10,5) NULL DEFAULT NULL,
  QMNor DECIMAL(10,5) NULL DEFAULT NULL,
  QMMin DECIMAL(10,5) NULL DEFAULT NULL,
  QNUnit VARCHAR(255) NULL DEFAULT NULL,
  QNMax DECIMAL(10,5) NULL DEFAULT NULL,
  QNNor DECIMAL(10,5) NULL DEFAULT NULL,
  QNMin DECIMAL(10,5) NULL DEFAULT NULL,
  PressureUnit VARCHAR(255) NULL DEFAULT NULL,
  InletPressureMaxQ DECIMAL(10,5) NULL DEFAULT NULL,
  InletPressureNorQ DECIMAL(10,5) NULL DEFAULT NULL,
  InletPressureMinQ DECIMAL(10,5) NULL DEFAULT NULL,
  OutletPressureMaxQ DECIMAL(10,5) NULL DEFAULT NULL,
  OutletPressureNorQ DECIMAL(10,5) NULL DEFAULT NULL,
  OutletPressureMinQ DECIMAL(10,5) NULL DEFAULT NULL,
  DifferentialPressureMaxQ DECIMAL(10,5) NULL DEFAULT NULL,
  DifferentialPressureNorQ DECIMAL(10,5) NULL DEFAULT NULL,
  DifferentialPressureMinQ DECIMAL(10,5) NULL DEFAULT NULL,
  TemperatureUnit VARCHAR(255) NULL DEFAULT NULL,
  InletTemperatureQ DECIMAL(10,5) NULL DEFAULT NULL,
  InletTemperatureNorQ DECIMAL(10,5) NULL DEFAULT NULL,
  InletTemperatureMinQ DECIMAL(10,5) NULL DEFAULT NULL,
  DensityUnit VARCHAR(255) NULL DEFAULT NULL,
  Density DECIMAL(10,5) NULL DEFAULT NULL,
  MolecularWeightUnit VARCHAR(255) NULL DEFAULT NULL,
  MolecularWeight DECIMAL(10,5) NULL DEFAULT NULL,
  CalculatedCvUnit VARCHAR(255) NULL DEFAULT NULL,
  CalculatedCvMaxQ DECIMAL(10,5) NULL DEFAULT NULL,
  CalculatedCvNorQ DECIMAL(10,5) NULL DEFAULT NULL,
  CalculatedCvMinQ DECIMAL(10,5) NULL DEFAULT NULL,
  SS100Max DECIMAL(10,5) NULL DEFAULT NULL,
  SS100Nor DECIMAL(10,5) NULL DEFAULT NULL,
  SS100Min DECIMAL(10,5) NULL DEFAULT NULL,
  U1Unit VARCHAR(255) NULL DEFAULT NULL,
  U1Max DECIMAL(10,5) NULL DEFAULT NULL,
  U1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  U1Min DECIMAL(10,5) NULL DEFAULT NULL,
  U2Max DECIMAL(10,5) NULL DEFAULT NULL,
  U2Nor DECIMAL(10,5) NULL DEFAULT NULL,
  U2Min DECIMAL(10,5) NULL DEFAULT NULL,
  LpAeMax DECIMAL(10,5) NULL DEFAULT NULL,
  LpAeNor DECIMAL(10,5) NULL DEFAULT NULL,
  LpAeMin DECIMAL(10,5) NULL DEFAULT NULL,
  WarningStateMax VARCHAR(255) NULL DEFAULT NULL,
  WarningStateNor VARCHAR(255) NULL DEFAULT NULL,
  WarningStateMin VARCHAR(255) NULL DEFAULT NULL,
  WarningTypeMax VARCHAR(255) NULL DEFAULT NULL,
  WarningTypeNor VARCHAR(255) NULL DEFAULT NULL,
  WarningTypeMin VARCHAR(255) NULL DEFAULT NULL,
  FluidPUnit VARCHAR(255) NULL DEFAULT NULL,
  FluidP1Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidP1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidP1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidP2Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidP2Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidP2Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidN1Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidN1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidN1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidN1Unit VARCHAR(255) NULL DEFAULT NULL,
  FluidV1Max DECIMAL(10,5) NULL DEFAULT NULL,
  Fluidv1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidV1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidV1Unit VARCHAR(255) NULL DEFAULT NULL,
  FluidPV1Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidPV1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidPV1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidPV1Unit VARCHAR(255) NULL DEFAULT NULL,
  FluidTV1Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidTV1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidTV1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidTV1Unit VARCHAR(255) NULL DEFAULT NULL,
  FluidCF1Max DECIMAL(10,5) NULL DEFAULT NULL,
  FluidCF1Nor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidCF1Min DECIMAL(10,5) NULL DEFAULT NULL,
  FluidCF1Unit VARCHAR(255) NULL DEFAULT NULL,
  FluidKMax DECIMAL(10,5) NULL DEFAULT NULL,
  FluidKNor DECIMAL(10,5) NULL DEFAULT NULL,
  FluidKMin DECIMAL(10,5) NULL DEFAULT NULL,
  ValveType CHAR(1) NULL DEFAULT NULL,
  FlowDirection VARCHAR(255) NULL DEFAULT NULL,
  ValvePerformClass VARCHAR(255) NULL DEFAULT NULL,
  Protection VARCHAR(255) NULL DEFAULT NULL,
  BasicCharacter VARCHAR(255) NULL DEFAULT NULL,
  TheoreticalRangeability DECIMAL(10,5) NULL DEFAULT NULL,
  FlowCoeffUnit VARCHAR(255) NULL DEFAULT NULL,
  FlowCoeff DECIMAL(10,5) NULL DEFAULT NULL,
  NorFlowCoeff DECIMAL(10,5) NULL DEFAULT NULL,
  SizePressureClass VARCHAR(255) NULL DEFAULT NULL,
  SuggestedValveSize DECIMAL(10,5) NULL DEFAULT NULL,
  BonnetType CHAR(1) NULL DEFAULT NULL,
  BodyMat CHAR(1) NULL DEFAULT NULL,
  BodySizeUnit CHAR(1) NULL DEFAULT NULL,
  BodySize CHAR(1) NULL DEFAULT NULL,
  Rating CHAR(1) NULL DEFAULT NULL,
  RatingUnit CHAR(1) NULL DEFAULT NULL,
  Connection CHAR(1) NULL DEFAULT NULL,
  CONVALTrim VARCHAR(255) NULL DEFAULT NULL,
  TrimType CHAR(1) NULL DEFAULT NULL,
  TrimSeries CHAR(1) NULL DEFAULT NULL,
  TrimMat CHAR(1) NULL DEFAULT NULL,
  TrimOption CHAR(1) NULL DEFAULT NULL,
  TrimPortSize CHAR(1) NULL DEFAULT NULL,
  TrimPortSizeUnit CHAR(1) NULL DEFAULT NULL,
  TrimForm CHAR(1) NULL DEFAULT NULL,
  ActType CHAR(1) NULL DEFAULT NULL,
  ActSeriesCode CHAR(1) NULL DEFAULT NULL,
  ActSize CHAR(1) NULL DEFAULT NULL,
  HW CHAR(1) NULL DEFAULT NULL,
  PosCode CHAR(1) NULL DEFAULT NULL,
  PosMakerCode CHAR(1) NULL DEFAULT NULL,
  SolCode CHAR(1) NULL DEFAULT NULL,
  SolMakerCode CHAR(1) NULL DEFAULT NULL,
  LimCode CHAR(1) NULL DEFAULT NULL,
  LimMakerCode CHAR(1) NULL DEFAULT NULL,
  ASCode CHAR(1) NULL DEFAULT NULL,
  ASMakerCode CHAR(1) NULL DEFAULT NULL,
  VolCode CHAR(1) NULL DEFAULT NULL,
  VolMakerCode CHAR(1) NULL DEFAULT NULL,
  AirOpCode CHAR(1) NULL DEFAULT NULL,
  AirOpMakerCode CHAR(1) NULL DEFAULT NULL,
  LockupCode CHAR(1) NULL DEFAULT NULL,
  LockupMakerCode CHAR(1) NULL DEFAULT NULL,
  SnapActCode CHAR(1) NULL DEFAULT NULL,
  SnapActMakerCode CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (TempEstimateNo, SheetID),
  CONSTRAINT FK_DataSheetLv3_TempEstimateNo FOREIGN KEY (TempEstimateNo) REFERENCES EstimateSheetLv1(TempEstimateNo) ON UPDATE CASCADE ON DELETE RESTRICT
);
